# Generated by Django 4.2.9 on 2024-02-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ("-publish_date",)},
        ),
        migrations.RemoveIndex(
            model_name="post",
            name="blog_app_po_title_818d20_idx",
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["-publish_date"], name="blog_app_po_publish_db007a_idx"),
        ),
    ]
